name: Build Unity client

on:
  workflow_dispatch:

jobs:
    build-unity:
        runs-on: self-hosted
        defaults:
          run:
            shell: bash
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                lfs: true
        
            - name: Cache Library folder
              uses: actions/cache@v3
              with:
                path: Library
                key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
                restore-keys: |
                  Library-

            - name: Build project
              uses: game-ci/unity-builder@v4
              env:
                UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
                UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
                UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}                
              with:
                targetPlatform: StandaloneWindows64
                customImage: unityci/editor:ubuntu-2022.3.9f1-linux-il2cpp-3.0.1
                # customImage: unityci/editor:ubuntu-2022.3.9f1-windows-mono-3.0.1
                # customImage: unityci/editor:windows-2022.3.9f1-windows-il2cpp-3.0.1
                # dockerWorkspacePath: \\github\\workspace
      
            - name: Upload build artifact
              uses: actions/upload-artifact@v3
              with:
                name: Build
                path: build

            - name: Upload to itch.io
              uses: robpc/itchio-upload-action@v1
              with:
                path: build
                project: "bhat-ganesh/test-megacity-sample"
                channel: "windows"
                version: ${{ github.run_number }}
                api-key: ${{ secrets.ITCHIO_API_KEY }}