name: Sandbox Workflow

on:
  workflow_dispatch:

jobs:
    sandbox:
        runs-on: [self-hosted, macOS]
        steps:
            - name: Run
              run: |
                  echo "Hello World"
                  echo "github.workspace = ${{ github.workspace }}"