name: Sandbox Workflow

on:
  workflow_dispatch:

jobs:
    sandbox:
        runs-on: self-hosted
        steps:
            - name: Run
              run: |
                  echo "Hello World"
                  echo "GITHUB_WORKSPACE = ${{ GITHUB_WORKSPACE }}"
                  echo "github.workspace = ${{ github.workspace }}"